exec: compile
	cd ../../../../../../ && mvn exec:java

clean:
	cd ../../../../../../ && mvn clean

compile:
	cd ../../../../../../ && mvn compile

test: clean
	cd ../../../../../../ && mvn test

cd-root-dir:
	cd ../../../../../../
